[version]
current = "0.1.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "chore: bumped version to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "src/minilsap/_version.py"
version_template = "{major}.{minor}.{patch}"
search = '__version__ = "{current_version}"'

[[before_commit]]
name = "Run tests"
cmd = ".venv/bin/pytest && pre-commit run --all-files"
